add code to remove versions
GSK-Biostatistics/slushy pull request #15
Opened 2024-04-04 08:47 UTC by alanahjonas95

resolves #13 

Hi Becca, not sure if this is exactly what we want but I've added some code to remove version info from the packages, by keeping the string before any @ sign, let me know if this is what we expected.
I've done this in slushy_init and slushy_add/slushy drop

2024-04-08 16:37 UTC, bzkrouse requested changes
Thanks for adding this functionality!! A couple comments for you, let me know if you have any questions!

2024-04-08 16:37 UTC, bzkrouse commented on R/slushy_init.R
> +  pkgs <- sapply(pkgs, function(x) strsplit(x, "@")[[1]][1])
```suggestion
```

2024-04-08 16:37 UTC, bzkrouse commented on R/slushy_init.R
> +  pkgs <- sapply(pkgs, function(x) strsplit(x, "@")[[1]][1])
this will not be necessary here, as the pkgs will get passed to renv::install as-is and work fine. The string manipulation is only needed when you get to modifying the DESCRIPTION file.

2024-04-08 16:37 UTC, bzkrouse commented on R/slushy_add.R
> +  installed_pkgs <- sapply(installed_pkgs, function(x) strsplit(x, "@")[[1]][1])
Two comments:

1. can you move this bit of string manipulation inside the `add_desc_deps()` helper instead, as it is specific to the DESCRIPTION file? This also means you will not need to repeat the code below for package removal. 
2. We can use a regex to make this code a little more readable by replacing the @ and everything after it with an empty string like so:
`gsub("@.*","", installed_pkgs)`

2024-04-09 10:00 UTC, alanahjonas95 commented on R/slushy_add.R
> +  installed_pkgs <- sapply(installed_pkgs, function(x) strsplit(x, "@")[[1]][1])
sure ive moved the code into: add_desc_deps() and updated to the method you've suggested in point 2 :)

2024-04-09 12:45 UTC, merged