create slushy_trim
GSK-Biostatistics/slushy pull request #37
Opened 2024-09-11 16:28 UTC by karima662

2024-09-12 19:31 UTC, bzkrouse requested changes
this is looking so great!! Just a couple of changes needed!

2024-09-12 19:31 UTC, bzkrouse commented on R/slushy_trim.R
> +             !str_detect(Source, regex("DESCRIPTION$", ignore_case = TRUE))) %>%
can you please also include renv.lock as it will show a dependency of renv

2024-09-12 19:31 UTC, bzkrouse commented on R/slushy_trim.R
> +                                         which = c("Depends", "Imports"),
I believe we also want to include "LinkingTo" here

2024-09-12 19:31 UTC, bzkrouse commented on R/slushy_trim.R
> +  pkgs_to_drop <- setdiff(proj_library_pkgs, pkgs_to_keep)
Can you figure out which of these are top-level packages (i.e. listed in DESCRIPTION)? We don't need to notify user that dependencies are being dropped, just top level packages.

2024-09-12 19:31 UTC, bzkrouse commented on R/slushy_trim.R
> +    cat("Would you like to proceed? \n1. Proceed \n2. Cancel \nSelection: ")
can you try utils::menu here instead? I think it will be simpler!

2024-09-12 19:31 UTC, bzkrouse commented on R/slushy_trim.R
> +      slushy_drop(pkgs_to_drop)
if you subset this to just the top-level packages above, we will need to check this effectively removes all deps we dont need anymore.

2024-09-12 19:31 UTC, bzkrouse commented on R/slushy_trim.R
> +    return(invisible(NULL))
```suggestion
```

this is covered by the last invisible(NULL) right?

2024-09-12 19:31 UTC, bzkrouse commented on R/slushy_trim.R
> +      slushy_drop(pkgs_to_drop)
```suggestion
      slushy_drop(pkgs_to_drop, restart = FALSE)
```

2024-09-16 15:57 UTC, karima662 commented on R/slushy_trim.R
> +             !str_detect(Source, regex("DESCRIPTION$", ignore_case = TRUE))) %>%
https://github.com/GSK-Biostatistics/slushy/pull/37/commits/cdce33bbefe614d3bfa07ad9825d66ba013e8538

2024-09-16 15:58 UTC, karima662 commented on R/slushy_trim.R
> +                                         which = c("Depends", "Imports"),
https://github.com/GSK-Biostatistics/slushy/pull/37/commits/c002c5e19503aa7c550c835f2e186a17d23878a4

2024-09-16 15:59 UTC, karima662 commented on R/slushy_trim.R
> +    cat("Would you like to proceed? \n1. Proceed \n2. Cancel \nSelection: ")
https://github.com/GSK-Biostatistics/slushy/pull/37/commits/7aca19fe05bc3f1c950d26ed56a3224883a1c82c

2024-09-16 16:11 UTC, karima662 commented on R/slushy_trim.R
> +    return(invisible(NULL))
https://github.com/GSK-Biostatistics/slushy/pull/37/commits/4c887d9f13ab0dc580c380ef8735d6ddf73bd524

2024-09-16 16:11 UTC, karima662 commented on R/slushy_trim.R
> +      slushy_drop(pkgs_to_drop)
https://github.com/GSK-Biostatistics/slushy/pull/37/commits/e43a8840659085a29d8e91741cb9db1e7f16aa71

2024-09-16 16:35 UTC, karima662 commented on R/slushy_trim.R
> +  pkgs_to_drop <- setdiff(proj_library_pkgs, pkgs_to_keep)
https://github.com/GSK-Biostatistics/slushy/pull/37/commits/3ed9ec9154b75aa07feb7bb2006d987d5cc947c5

created a new list `desc_pkgs` of description packages and `pkgs_to_drop_top_level` which identifies the pkgs in common between `desc_pkgs` and `pkgs_to_drop`. The `pkgs_to_drop_top_level` are output in the message to the user but the `pkgs_to_drop` (top-level plus deps) are the ones being removed in the background.

2024-09-16 16:36 UTC, karima662 commented on R/slushy_trim.R
> +  pkgs_to_drop <- setdiff(proj_library_pkgs, pkgs_to_keep)
Happy to make changes if this isn't what you had in mind

2024-09-16 16:36 UTC, karima662 commented on R/slushy_trim.R
> +      slushy_drop(pkgs_to_drop)
Please see comment in https://github.com/GSK-Biostatistics/slushy/pull/37#discussion_r1761479991

2024-09-17 14:12 UTC, bzkrouse approved these changes
this looks really great, thank you!!!

2024-09-17 17:17 UTC, merged