Add user-supplied config file to gitignore
GSK-Biostatistics/slushy pull request #41
Opened 2024-09-24 13:58 UTC by karima662

addressing #27 

Logic of changes made:
- save name of config file supplied to `get_config()` in `slushy_init()` as an attribute "config_file_name" to `config_list`
- call `config_file_name` from the `config` param in `slushy_init()`
- supply this to the newly added `update_ignores(additional_unignore_files = ...)` param
- within this function, an exclamation mark is prepended to `additional_unignore_files` and then appended to `renv_files`

2024-10-02 13:11 UTC, bzkrouse commented on R/config.R
>    config <- config::get(value = "config_name", config = "default", file = config_file)
```suggestion
  config <- get(value = "config_name", config = "default", file = config_file)
```

2024-10-02 13:38 UTC, bzkrouse requested changes
looks great, just a couple changes :)

2024-10-02 13:38 UTC, bzkrouse commented on R/config.R
> +  config_list <- config::get(value = config, config = "default", file = config_file)
```suggestion
  config_list <- get(value = config, config = "default", file = config_file)
```

2024-10-02 13:38 UTC, bzkrouse commented on R/config.R
> +  attr(config_list, "config_file_name") <- config_file
```suggestion
  structure(config_list,
                 config_file_name = config_file)
```

2024-10-02 13:38 UTC, bzkrouse commented on R/config.R
> +  return(config_list)
```suggestion
```

2024-10-02 13:38 UTC, bzkrouse commented on R/slushy_trim.R
> +slushy_trim <- function(project = NULL, config = get_config()) {
I like this, can we add it to the other functions as well?

2024-10-02 13:44 UTC, karima662 commented on R/slushy_trim.R
> +slushy_trim <- function(project = NULL, config = get_config()) {
just to clarify - would you prefer to have `slushy_config.yml` as the default or empty (for each function)?

2024-10-02 14:01 UTC, bzkrouse commented on R/slushy_trim.R
> +slushy_trim <- function(project = NULL, config = get_config()) {
empty is good, since get_config is an exported function so people can easily see the default!

2024-10-21 20:01 UTC, bzkrouse requested changes
Looks great!!! Can you please also update the NEWS file since this is a user-facing change?

2024-10-22 13:26 UTC, bzkrouse commented on NEWS.md
> +- Add user-supplied configuration file to be in the `gitignore` file
just this line to describe the user-facing change is perfect, thank you :) You can remove the other lines.

2024-10-22 19:39 UTC, bzkrouse commented on NEWS.md
>  # slushy development 0.5.2.9000
```suggestion
```

2024-10-24 12:44 UTC, bzkrouse commented on R/config.R
> +  # return the configuration list with the attached attribute
```suggestion
  # return the configuration list with the attached attribute
```

2024-10-24 12:45 UTC, bzkrouse approved these changes

2024-10-24 13:17 UTC, merged