create `slushy_log()` function
GSK-Biostatistics/slushy pull request #44
Opened 2024-11-25 18:18 UTC by karima662

addressing #20

2024-12-06 17:08 UTC, karima662 commented
You can use this to check output:

```r
library(slushy)

slushy_init(config = get_config(config_file = "slushy_config.yml"))
slushy_add("viridis", config = get_config(config_file = "slushy_config.yml"))
slushy_drop("forcats", restart = FALSE)

slushy_log(config = get_config(config_file = "slushy_config.yml"), full_report = FALSE) # default
slushy_log(config = get_config(config_file = "slushy_config.yml"), full_report = TRUE)
```

2024-12-09 18:03 UTC, bzkrouse requested changes
Amazing work!!!
I added some comments for things that could use a tweak. 
The other request I have is breaking the `slushy_log()` function down into multiple smaller functions, to be wrapped in the `slushy_log()` call. Would that be doable?
Happy to chat further!

2024-12-09 18:04 UTC, bzkrouse commented on R/slushy_log.R
> +    cli_h3("DESCRIPTION Packages Used")
```suggestion
    cli_h3("Agreed-upon Packages Used")
```

2024-12-09 18:06 UTC, bzkrouse commented on R/slushy_log.R
> +    cli_alert_info("Packages in DESCRIPTION that are being used in code: {length(desc_pkgs_used)}")
```suggestion
    cli_alert_info("Agreed-upon packages that are being used in code: {length(desc_pkgs_used)}")
```

2024-12-09 18:07 UTC, bzkrouse commented on R/slushy_log.R
> +    cli_alert_info("Packages in DESCRIPTION that are not being used in code: {length(desc_pkgs_not_used)}")
```suggestion
    cli_alert_info("Agreed-upon packages that are not being used in code: {length(desc_pkgs_not_used)}")
```

2024-12-09 18:08 UTC, bzkrouse commented on R/slushy_log.R
> +    cli_h3("Packages Added or Removed")
```suggestion
    cli_h3("Agreed-Upon Packages Added or Removed")
```

2024-12-09 18:10 UTC, bzkrouse commented on R/slushy_log.R
> +    cli_alert_info("Added packages not in config file: {length(pkgs_added)}")
```suggestion
    cli_alert_info("Agreed-upon packages added since slushy initialization: {length(pkgs_added)}")
```

2024-12-09 18:10 UTC, bzkrouse commented on R/slushy_log.R
> +    cli_alert_info("Removed packages not in DESCRIPTION file: {length(pkgs_removed)}")
```suggestion
    cli_alert_info("Agreed-upon packages removed since slushy initialization: {length(pkgs_removed)}")
```

2024-12-09 18:11 UTC, bzkrouse commented on R/slushy_log.R
> +    cli_h3("Comparing Used Packages")
```suggestion
    cli_h3("Detecting Use of Packages Outside the Agreed-Upon Set")
```

2024-12-09 18:12 UTC, bzkrouse commented on R/slushy_log.R
> +    cli_alert_info("Used Packages that are not in DESCRIPTION nor its dependencies:")
```suggestion
    cli_alert_info("Used packages that are not in the agreed-upon packages nor their dependencies:")
```

2024-12-10 15:50 UTC, bzkrouse commented
> * I'm wondering if we need more conditional logic in the print-out. For example, if no unapproved packages are detected, it still prints the header for that piece with an empty output. Maybe that's fine, but maybe we want a "none found" or something.
> * Did you explore using cli for all the lines of the print-out? there seem to be various places with just a `print()`. This could also help with conditional logic mentioned above.

https://cli.r-lib.org/articles/pluralization.html

2024-12-16 20:25 UTC, karima662 commented on R/slushy_log.R
> +#' `renv::diagnostics` by default and can generate a custom report comparing
edit made here: https://github.com/GSK-Biostatistics/slushy/pull/44/commits/f3b790d8cdc890951125670d6ca0d1cfe1ffb535

2025-01-10 19:18 UTC, karima662 commented on R/slushy_log.R
> +  lib_not_lock <- setdiff(library_df_pkgs, lockfile_df_pkgs) %>% setdiff(rec_op_pkgs)
```r
lib_not_lock <- setdiff(library_df_pkgs, lockfile_df_pkgs) %>% setdiff(rec_op_pkgs)
lock_not_lib <- setdiff(lockfile_df_pkgs, library_df_pkgs) %>% setdiff(rec_op_pkgs)
```
these two pkg lists were included as a sort of internal check in case we need to debug in future - not sure if I should make it an if statement or just remove?

2025-01-10 19:27 UTC, karima662 commented on R/slushy_log.R
> +    filter(version_match == FALSE | is.na(version_match) == TRUE)
The code on lines 82-83 drop packages where there is no mismatch. Inversely, it selects packages where there is a mismatch (match is FALSE) or undefined (NA present).

Example of what `inst_vs_avail_subset` might look like:

![image](https://github.com/user-attachments/assets/1f7dd0e9-57cf-477f-a1b7-657467c25e45)

2025-01-10 19:35 UTC, bzkrouse commented on R/slushy_log.R
> +  lib_not_lock <- setdiff(library_df_pkgs, lockfile_df_pkgs) %>% setdiff(rec_op_pkgs)
@karima662 I'm ok removing! I think you should be able to get something similar via renv::status if you need to..

2025-01-10 19:40 UTC, karima662 commented on R/slushy_log.R
> +  lib_not_lock <- setdiff(library_df_pkgs, lockfile_df_pkgs) %>% setdiff(rec_op_pkgs)
change made here: https://github.com/GSK-Biostatistics/slushy/pull/44/commits/1af83a9bfc61910a17c8e035adb85d03f377090c

2025-01-10 19:41 UTC, karima662 commented
> > * I'm wondering if we need more conditional logic in the print-out. For example, if no unapproved packages are detected, it still prints the header for that piece with an empty output. Maybe that's fine, but maybe we want a "none found" or something.
> > * Did you explore using cli for all the lines of the print-out? there seem to be various places with just a `print()`. This could also help with conditional logic mentioned above.
> 
> https://cli.r-lib.org/articles/pluralization.html

issue made for this here #50

2025-01-13 19:35 UTC, bzkrouse commented
@karima662 Just tested this and it's super close!! Just a couple more refinements that are hopefully quick:

1. for the "Agreed-upon packages added following slushy initialization", can you please omit slushy and renv from this? (slushy is appearing for me)
2. I think we can remove the section "detecting use of packages outside the agreed-upon set" as the section that follows ("used packages outside the agreed upon set") is sufficient for the user. 
3. The function returns a NULL value, I think because of the use of `print()` for the full message as opposed to `cat()` or `cli_*()`. Can you please tweak so it doesn't return NULL?

Let me know if you have any questions!

2025-01-14 18:57 UTC, bzkrouse commented
@karima662 Great work thank you so much!

2025-01-14 18:58 UTC, bzkrouse approved these changes

2025-01-14 18:58 UTC, merged